apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-provisioner-localpath
  labels:
    app: external-provisioner-localpath
  # replace with namespace where provisioner is deployed
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-provisioner-localpath
  template:
    metadata:
      labels:
        app: external-provisioner-localpath
    spec:
      serviceAccountName: external-provisioner
      containers:
        - name: external-provisioner-localpath
          image: 192.168.100.105/storage/external-provisioner-localpath:v0.0.1
          env:
            - name: PROVISIONER_NAME
              value: external-provisioner-localpath
            - name: LOCAL_PATH
              value: /data/external-provisioner-localpath

